version: "3.3"

services:
  ra-news:
    image: ghcr.io/stadia/ra-news:main
    container_name: ra-news
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SOLID_QUEUE_IN_PUMA=true
      - RAILS_LOG_LEVEL=debug
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.news.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.news-https.redirectscheme.scheme=https"
      - "traefik.http.routers.news-http.entrypoints=web"
      - "traefik.http.routers.news-http.middlewares=news-https"
      - "traefik.http.routers.news-http.rule=Host(`ruby-news.kr`)"
      - "traefik.http.routers.news.entrypoints=websecure"
      - "traefik.http.routers.news.rule=Host(`ruby-news.kr`)"
      - "traefik.http.routers.news.tls.certresolver=letsencrypt"
    networks:
      - homeNetwork
    restart: unless-stopped
  db:
    image: postgres:17
    container_name: postgresql
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    network_mode: host

networks:
  homeNetwork:
    external: true

volumes:
  postgresql_data:
    external: true
