production:
  rss_site_job:
    class:
    command: "RssSiteJob.enqueue_all"
    schedule: "0 7 * * *"
  gmail_article_job:
    command: "GmailArticleJob.enqueue_all"
    schedule: "0 10 * * 1-5"
  youtube_site_job:
    command: "YoutubeSiteJob.enqueue_all"
    schedule: "0 8 * * *"
  hacker_news_job:
    class: HackerNewsSiteJob
    schedule: "0 0,12 * * *"
  rss_site_page_job:
    class:
    command: "RssSitePageJob.enqueue_all"
    schedule: "0 6 * * *"
  sitemap_refresh:
      command: "SitemapService.call"
      schedule: "30/* * * *"
