production:
  rss_site_job:
    class: RssSiteJob
    schedule: "0 7 * * *"
  gmail_article_job:
    class: GmailArticleJob
    schedule: "0 10 * * 2"
  youtube_site_job:
    class: YoutubeSiteJob
    schedule: "0 8 * * *"
