production:
  rss_site_job:
    class: RssSiteJob
    schedule: "0 7 * * *"
  gmail_article_job:
    class: GmailArticleJob
    schedule: "0 10 * * 2"
  youtube_channel_job:
    class: YoutubeChannelJob
    schedule: "0 8 * * *"
