production:
  rss_site_job:
    command: "RssSiteJob.enqueue_all"
    schedule: "0 7 * * *"
  gmail_article_job:
    command: "GmailArticleJob.enqueue_all"
    schedule: "0 10 * * 1-5"
  youtube_site_job:
    command: "YoutubeSiteJob.enqueue_all"
    schedule: "0 8 * * *"
  hacker_news_job:
    class: HackerNewsSiteJob
    schedule: "10 */2 * * *"
  rss_site_page_job:
    command: "RssSitePageJob.enqueue_all"
    schedule: "0 6 * * *"
  sitemap_refresh:
    command: "SitemapService.call"
    schedule: "30 * * * 1-5"
  article_batch_job:
    class: "ArticleBatchJob"
    schedule: "0 */1 * * *"
  social_post_job:
    class: "SocialPostJob"
    schedule: "30 */1 * * *"
